version: '2'
services:

  §§INSTANCE-orientdb:
    image: orientdb:2.1.25
    container_name: §§INSTANCE-orientdb
    ports:
      - "§§PORT1:2480"
      - "§§PORT2:2424"
    environment:
      ES_JAVA_OPTS: '-Xmx8g'
      ORIENTDB_ROOT_PASSWORD: §§ORIENTDB_ROOT_PASSWORD
      ORIENTDB_NODE_NAME: 'node1'
    depends_on:
       - §§INSTANCE-orientdb-data
    volumes_from: 
       - §§INSTANCE-orientdb-data
    restart: unless-stopped
    command: "/orientdb/bin/dserver.sh -Dnetwork.maxConcurrentSessions=2000 -Dstorage.diskCache.bufferSize=6000"

  §§INSTANCE-orientdb-data:
    image: busybox
    container_name: §§INSTANCE-orientdb-data
    volumes:
       - ./data/orientdb/config:/orientdb/config
       - ./data/orientdb/databases:/orientdb/databases 
       - ./data/orientdb/backup:/orientdb/backup
